---
title: "PCA"
author: "Wagner Faria Barbosa"
date: "2022-08-18"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Packages

```{r message=FALSE, warning=FALSE}
library(factoextra)
library(FactoMineR)
```

## Reading data

```{r}
pca <- PCA(iris[,-5],  graph = FALSE)
```

## Getting eingen values

```{r}
get_eig(pca)
```

## Eigenvalues/variances

```{r}
fviz_screeplot(pca, addlabels = TRUE, ylim = c(0, 50))
```

## Graphical vizualizations

### Variables

```{r}
# Control variable colors using their contributions
fviz_pca_var(pca, col.var="contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE # Avoid text overlapping
             )
```

### Individuals

```{r}
fviz_pca_ind(pca,
             label = "none", # hide individual labels
             habillage = iris$Species, # color by groups
             palette = c("#00AFBB", "#E7B800", "#FC4E07"),
             addEllipses = TRUE # Concentration ellipses
             )
```

How is everything?
